### ISSUE TITLE
Unexpected exceptions

### ISSUE THREAD

**Issue by annabeth495** [ASSNAKE/assnake-dada2#2]
I have been trying to run script that counts the number of reads for samples, but the script produces error:
MissingRuleException:
No rule to produce PATH//sample/sample_R1.count (if you use input functions make sure that they don't raise unexpected exceptions).

How can I resolve that problem?

**Comment by Fedorov113** [comment]
Could you please share the exact command you are trying to execute?
Are you on the latest master version of [assnake](https://github.com/ASSNAKE/assnake) and [assnake-core-preprocessing](https://github.com/ASSNAKE/assnake-core-preprocessing)?

**Comment by annabeth495** [comment]
*assnake result count -d SETNAME -p raw run -t 1 -j 10 --run*

вт, 16 июн. 2020 г. в 14:03, Dmitry Fedorov <notifications@github.com>:

**Comment by Fedorov113** [comment]
@annabeth495 I can see that you use an old version. Please `git pull` in all assnake packages. In new CLI the first `run` was replaced with `gather`, so the command looks like ` assnake result count -d SETNAME -p raw gather -t 1 -j 10 --run`.
Please, feel free to write me on Telegram ( Trypsin )

**Comment by Fedorov113** [comment]
This was caused by broken links to read files.
